// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEezQRi5kMLdkvSiIRBoGR5rCcTLcPeXw',
    appId: '1:221370135226:web:4e395abf5b5b3448a80883',
    messagingSenderId: '221370135226',
    projectId: 'blinkora-8bded',
    authDomain: 'blinkora-8bded.firebaseapp.com',
    storageBucket: 'blinkora-8bded.firebasestorage.app',
    measurementId: 'G-9MX5ZD4JQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7quvYsMikJV3HQgMUYR-zj5qEZ4uajgM',
    appId: '1:221370135226:android:ff4a9ef9f5605693a80883',
    messagingSenderId: '221370135226',
    projectId: 'blinkora-8bded',
    storageBucket: 'blinkora-8bded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeVoaW8P9BO0uNotiM-TTJr-kOdIf_Ols',
    appId: '1:221370135226:ios:699d36a029a5eb30a80883',
    messagingSenderId: '221370135226',
    projectId: 'blinkora-8bded',
    storageBucket: 'blinkora-8bded.firebasestorage.app',
    iosBundleId: 'com.example.mod2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeVoaW8P9BO0uNotiM-TTJr-kOdIf_Ols',
    appId: '1:221370135226:ios:699d36a029a5eb30a80883',
    messagingSenderId: '221370135226',
    projectId: 'blinkora-8bded',
    storageBucket: 'blinkora-8bded.firebasestorage.app',
    iosBundleId: 'com.example.mod2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEezQRi5kMLdkvSiIRBoGR5rCcTLcPeXw',
    appId: '1:221370135226:web:b237f9b7c5f3aa88a80883',
    messagingSenderId: '221370135226',
    projectId: 'blinkora-8bded',
    authDomain: 'blinkora-8bded.firebaseapp.com',
    storageBucket: 'blinkora-8bded.firebasestorage.app',
    measurementId: 'G-XQ7CGWLC1E',
  );

}